### ISSUE TITLE
Failed to build python wrapper 

### ISSUE THREAD

**Issue by lucasgiacobo** [IntelRealSense/RealSenseID#102] opened 2021-07-26 11:22 UTC
I follow the instructions to build the python wrapper, but when i try to build give me the error below: 

![Screenshot from 2021-07-26 08-14-52](https://user-images.githubusercontent.com/46139516/126980740-dead426e-72fd-4487-a714-7f4da1661b9a.png)

Ubuntu 20.04.2 LTS

**Comment by gabime** [comment] 2021-07-26 11:24
Duplicate of #101 . Will be fix in next release

**Comment by gabime** [comment] 2021-07-27 11:16
Released in version 0.23.0

**Closed by gabime** 2021-07-27 11:16 UTC
